### ISSUE TITLE
Elm package hash changes

### ISSUE THREAD

**Issue by samjeffress** [hayleigh-dot-dev/tuple-extra#2]
We had the following error when rebuilding today - this could be because of the rename of your github profile from https://github.com/pd-andy/tuple-extra/ --> https://github.com/hayleigh-dot-dev/tuple-extra/

Are you able to publish new packages with the updated git path?

```
-- CORRUPT PACKAGE DATA --------------------------------------------------------
I downloaded the source code for pd-andy/tuple-extra 1.0.1 from:
    https://github.com/pd-andy/tuple-extra/zipball/1.0.1/
But it looks like the hash of the archive has changed since publication:
  Expected: 6bd6ce2f36fb048f2925fd73cca4b2e41bb3538f
    Actual: 6a2f881639dcce1473eb9c200c71d88e4b116e86
This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
```

**Comment by hayleigh-dot-dev** [comment]
You can grab the package at `hayleigh-dot-dev/tuple-extra` now. It's back at `1.0.0`, because Elm doesn't really have any way of handling GitHub username changes!
